### ISSUE TITLE
应当进行冗余上报，或在 TimeOut 后再次尝试上报

### ISSUE THREAD

**Issue by Sciroccogti** [luzy99/SEUAutoLogin#12]
![图片](https://user-images.githubusercontent.com/32357397/132449696-871161bf-97ba-440f-aaa6-dceeeaa3ae76.png)

存在 TimeOut 的可能，导致我有一天没上报（

**Comment by luzy99** [comment]
之前也遇到过上报失败的情况，估计是运行节点被seu墙了，同一任务中重试也无法成功，暂时没想到解决方案。
不过运行失败GitHub会邮件通知吧，就只能手动填报喽

**Comment by Sciroccogti** [comment]
所以我就一天自动上报三次（

**Comment by luzy99** [comment]
有道理，确实也是一种解决方案，但毕竟小概率事件，懒得改了）
