### ISSUE TITLE
多高校打卡合作邀请

### ISSUE THREAD

**Issue by mrcaidev** [luzy99/SEUAutoLogin#16]
朋友您好！

我是[电子科技大学自动打卡](https://github.com/mrcaidev/thermoflash)项目的作者，现欲开发一款各高校通用的、基于 GitHub Actions 的自动打卡工具；目前框架与主程序都已初步搭建完毕，后续的开发者只需要编写插件即可。

一位朋友向我推荐了您的项目。拜读之后，我觉得您的代码水平与逻辑都十分地优秀且可靠，不知您是否愿意了解一下[上述的项目](https://github.com/mrcaidev/thermoflash)；如果能参与开发，更是我的荣幸。您随时可以通过 QQ 联系我：1014305148。

期待与您的合作，相互学习、共同进步！

**Comment by luzy99** [comment]
非常感谢您对本项目的认可！非常抱歉，出于以下几点考量，暂不做与贵项目整合的打算：
1. 就本项目而言，本人仅出于学习的目的而作，没有做推广的打算。
2. 出于安全性考虑，自动打卡涉及到各个高校网站的登录鉴权等敏感操作，整合起来可能会增大隐私泄露的风险。
3. 一些个人拙见：拜读了您的项目，觉得您的代码结构很清晰，可拓展性很强，但不太清楚您是不是希望将各个高校的上报逻辑以插件形式整合在同一个项目中。我觉得由于每个学校的上报流程关联性不大，为了便于使用和维护，以您的项目为模板，在独立的仓库中进行二次开发部署更为合适。

**Comment by mrcaidev** [comment]
感谢您的回复，意见收到！
