### ISSUE TITLE
作者大大，在哪里修改每日打卡的时间啊？

### ISSUE THREAD

**Issue by xmasrain** [luzy99/SEUAutoLogin#18]
作者大大，在哪里修改每日打卡的时间啊？能自行修改吗？

**Comment by Sciroccogti** [comment]
https://github.com/luzy99/SEUAutoLogin/blob/28ba3a5d271c5f2e7490031b1e739834c5ef5466/.github/workflows/daily-report.yml#L11

这边，是 UTC 时间，32 0 表示 UTC 时间0点32分。

**Comment by xmasrain** [comment]
UTC 时间0点32分，应该是对应北京时间8:32，那为什么每天都是在早上10:00自动打卡啊？

**Comment by Sciroccogti** [comment]
> UTC 时间0点32分，应该是对应北京时间8:32，那为什么每天都是在早上10:00自动打卡啊？

github action 好像要排队，不会那么准时。

**Comment by xmasrain** [comment]
如果我修改成： - cron: "32 22 * * *" 
是代表UTC 时间22点32分吗？对应北京时间6:32？

**Comment by Sciroccogti** [comment]
是的，但是建议不要设定这么早，印象里太早的话会上报失败。
