### ISSUE TITLE
现在获取隐藏值的get请求，需要添加正确的headers了

### ISSUE THREAD

**Issue by Waikkii** [luzy99/SEUAutoLogin#21]
如题

**Comment by Waikkii** [comment]
而且，现在通过post登录之后，[http://ehall.seu.edu.cn/jsonp/userDesktopInfo.json]，这个请求仍然无法获取信息，包括其他ehall的操作貌似都显示尚未登陆，感觉像是缺了某个逻辑。

**Comment by Waikkii** [comment]
目前测试下来，学校内网没有问题，headers的问题也没有。但是开代理、热点、服务器、action等就会有上述问题，尚不知道如何鉴权。

**Comment by luzy99** [comment]
感谢反馈，正在排查。

**Comment by luzy99** [comment]
已对session添加headers，经本地验证，问题已修复，待明日action验证 https://github.com/luzy99/SEUAutoLogin/commit/f884c865b24648e88f47f3623f35976f9fa4a373

**Comment by hht980309** [comment]
似乎在action下仍无法登陆

**Comment by luzy99** [comment]
@Sciroccogti 这个问题烦请您帮忙跟进下吧，我跑路了，明天就没打卡权限了😏
我本地代理、热点可登录，就action不行，很怪

**Comment by Sciroccogti** [comment]
> @Sciroccogti 这个问题烦请您帮忙跟进下吧，我跑路了，明天就没打卡权限了😏 我本地代理、热点可登录，就action不行，很怪

只能等考完试研究研究了

**Comment by Waikkii** [comment]
一说学校可能在换ssl证书，二说学校网站被玄武盾拦截了，不得而知，目前action和云服务器都不行。

**Comment by 469maPabu** [comment]
我改了一下login.py里的headers，好像可以用了？明天再试试。
运行结果：
![image](https://user-images.githubusercontent.com/106329989/175543969-e4282af0-cd33-4d01-a5f3-c6677efee509.png)
修改的部分：去掉了host，加了'Content-Type': 'application/x-www-form-urlencoded'
![image](https://user-images.githubusercontent.com/106329989/175544223-e394e5e6-123c-4bf5-917f-796e6faa138d.png)

**Comment by Waikkii** [comment]
> 我改了一下login.py里的headers，好像可以用了？明天再试试。 运行结果： ![image](https://user-images.githubusercontent.com/106329989/175543969-e4282af0-cd33-4d01-a5f3-c6677efee509.png) 修改的部分：去掉了host，加了'Content-Type': 'application/x-www-form-urlencoded' ![image](https://user-images.githubusercontent.com/106329989/175544223-e394e5e6-123c-4bf5-917f-796e6faa138d.png)

确实只需要这两个key，
我添加了ss.headers = headers
修改了res = ss.get(url, headers=headers)和res = ss.post(url, data=form, headers=headers)就可以在服务器上跑了
![image](https://user-images.githubusercontent.com/50266226/175545647-bc844dbd-9b60-4400-8bea-d12e815fee20.png)

**Comment by Sciroccogti** [comment]
> 我改了一下login.py里的headers，好像可以用了？

我这里测试也OK

**Comment by Southwind497** [comment]
> 我改了一下login.py里的headers，好像可以用了？

感谢，可以正常运行了

**Comment by Sciroccogti** [comment]
> 我改了一下login.py里的headers，好像可以用了？

是否考虑提交一个 PR ？

**Comment by 469maPabu** [comment]
> > 我改了一下login.py里的headers，好像可以用了？
> 
> 是否考虑提交一个 PR ？

提交了#24

**Comment by xmasrain** [comment]
自动打卡还是不行诶

**Comment by Iordofwar** [comment]
> > 我改了一下login.py里的headers，好像可以用了？明天再试试。 运行结果： ![image](https://user-images.githubusercontent.com/106329989/175543969-e4282af0-cd33-4d01-a5f3-c6677efee509.png) 修改的部分：去掉了host，加了'Content-Type': 'application/x-www-form-urlencoded' ![image](https://user-images.githubusercontent.com/106329989/175544223-e394e5e6-123c-4bf5-917f-796e6faa138d.png)
> 
> 确实只需要这两个key， 我添加了ss.headers = headers 修改了res = ss.get(url, headers=headers)和res = ss.post(url, data=form, headers=headers)就可以在服务器上跑了 ![image](https://user-images.githubusercontent.com/50266226/175545647-bc844dbd-9b60-4400-8bea-d12e815fee20.png)

可以分享下你这个请假销假的代码吗

**Comment by Sciroccogti** [comment]
> 自动打卡还是不行诶

是否有重新 Fetch upstream？
![image](https://user-images.githubusercontent.com/32357397/177103244-65f97a9e-91cf-422f-9f25-887a06b49b4e.png)

**Comment by xmasrain** [comment]
> > 自动打卡还是不行诶
> 
> 是否有重新 Fetch upstream？ ![image](https://user-images.githubusercontent.com/32357397/177103244-65f97a9e-91cf-422f-9f25-887a06b49b4e.png)

果然好了，建议放到readme的说明中。

**Comment by Sciroccogti** [comment]
> 果然好了，建议放到readme的说明中。

已在 506e68b 中添加。

**Comment by Waikkii** [comment]
> > > 我改了一下login.py里的headers，好像可以用了？明天再试试。 运行结果： ![image](https://user-images.githubusercontent.com/106329989/175543969-e4282af0-cd33-4d01-a5f3-c6677efee509.png) 修改的部分：去掉了host，加了'Content-Type': 'application/x-www-form-urlencoded' ![image](https://user-images.githubusercontent.com/106329989/175544223-e394e5e6-123c-4bf5-917f-796e6faa138d.png)
> > 
> > 
> > 确实只需要这两个key， 我添加了ss.headers = headers 修改了res = ss.get(url, headers=headers)和res = ss.post(url, data=form, headers=headers)就可以在服务器上跑了 ![image](https://user-images.githubusercontent.com/50266226/175545647-bc844dbd-9b60-4400-8bea-d12e815fee20.png)
> 
> 可以分享下你这个请假销假的代码吗

你可以参考我半年前写的这个
https://github.com/Waikkii/SEU_LOGIN/blob/main/leave.py
